/* =========================================================
   CYBERDOLL — product catalogue
   One place for every piece: the shop and the product page
   read from here. To add a product, copy a block, change the
   values and drop the photo in /img.

   cat:    tops | corsets | bottoms | dresses | knitwear | outerwear | shoes | accessories
   focus:  [x%, y%] — where the garment sits in the photo. Used to
           centre the card crop and the detail zooms on the product page.
   drop:   a number ("005") for drops, or "core" for the always-available collection.
           New In only shows the latest numbered drop.
   gallery (optional): extra photos, e.g. ["img/tops/top-03-back.jpg"].
           They show up on the product page before the detail zooms.
   ========================================================= */
(() => {
  const CLOTHES = ["XS", "S", "M", "L"];
  const SHOES = ["36", "37", "38", "39", "40"];
  const ONE = ["ONE SIZE"];

  window.CD_CATEGORIES = [
    { id: "tops", label: "TOPS" },
    { id: "corsets", label: "CORSETS" },
    { id: "bottoms", label: "BOTTOMS" },
    { id: "dresses", label: "DRESSES" },
    { id: "knitwear", label: "KNITWEAR" },
    { id: "outerwear", label: "OUTERWEAR" },
    { id: "shoes", label: "SHOES" },
    { id: "accessories", label: "ACCESSORIES" }
  ];

  window.CD_LOOKS = {
    hazardous: ["star-girl-earrings", "holy-studs-top", "fur-real-jacket", "buckle-up-shorts", "stomp-buckle-boots"],
    // DROP #005 · MIDNIGHT MALL — the three moods on new-in.html
    glitter: ["sweetest-girls-tank", "stardust-cowl-halter", "molten-metal-halter", "liquid-silver-fringe", "snow-leopard-tube", "rhinestone-riot-tee", "swirl-girl-halter", "bad-angel-tube"],
    studs: ["varsity-halter-corset", "crucifix-studded-corset", "safety-pin-slashed-tank", "skull-studs-rib-tank", "cathedral-lace-cami", "night-racer-baby-tee", "bleached-rockstar-tee", "stripe-layer-longsleeve", "pinstripe-prefect-shirt"],
    wild: ["wild-thing-halter", "leopard-halter-bandeau", "snake-charmer-rib-tank", "off-duty-slouch-knit", "rebel-print-slouch-tee"],
    laced: ["buckle-collar-corset", "grunge-grommet-corset", "leopard-lace-bustier", "vampira-lace-corset", "wildcat-satin-corset", "chain-reaction-corset", "lasercut-longsleeve-corset", "peekaboo-mesh-corset", "worn-leather-bustier"],
    lowrise: ["laced-up-flare-jeans", "yeti-flare-jeans", "fur-hem-denim-mini", "swirl-tattoo-jeans", "leopard-rara-mini", "gold-rush-flares", "chain-fur-shorts", "shredded-gyaru-jeans", "smoke-sheer-flares", "frayed-denim-micro", "gilded-bootcut-jeans", "mocha-cargo-lowrise"]
  };

  // every release, newest first — used by drops.html (and the shop's ?drop= filter)
  window.CD_DROPS = [
    { id: "006", name: "??????????", date: "13.11.2026", unlock: "2026-11-13T18:00:00", status: "LOCKED", locked: true,
      tagline: "something is loading…",
      desc: "Nobody knows yet. Not even us (ok, we know). Unlocks Friday the 13th at 18:00." },
    { id: "005", name: "MIDNIGHT MALL", date: "23.09.2026", status: "OUT NOW", color: "#ff5ea8", link: "new-in.html",
      tagline: "the 2004 mall at closing time",
      desc: "Cheap glitter, real leather attitude, leopard everywhere. Tops, corsets and low-rise bottoms in five moods." },
    { id: "004", name: "ANGEL.EXE", date: "05.06.2026", status: "LOW STOCK", color: "#9fc4e8",
      tagline: "corsets that look like error messages",
      desc: "Laced denim, skull knits, a chrome heart skirt and platform boots. The drop that crashed our server (twice)." },
    { id: "003", name: "HAZARDOUS", date: "14.02.2026", status: "ALMOST GONE", color: "#ff2a2a",
      tagline: "a valentine you can't return",
      desc: "One look, five pieces: star earrings, a studded cross top, a fur-hood jacket, buckle shorts and wrap boots." }
  ];

  // the lookbook — photos in /img, "pieces" are similar items from the catalogue
  window.CD_LOOKBOOK = {
    issue: "05", season: "SS'26", title: "MIDNIGHT FICTION",
    looks: [
      { id: "look-01", img: "img/look-01.jpg", title: "ANGELIC HEART", time: "23:47", place: "back door, club toilets",
        quote: "pretty is a weapon", note: "Polka mesh, a silver belt and platforms tall enough to see over the bouncer.",
        pieces: ["rhinestone-rodeo-belt", "tank-platform-boots", "leopard-pyramid-cuffs", "buckle-up-shorts"] },
      { id: "look-02", img: "img/look-02.jpg", title: "SPIKED", time: "00:31", place: "underpass, level -2",
        quote: "don't touch the hat", note: "Every surface studded. Leather corset, wrapped belts, fur at the ankles.",
        pieces: ["spiked-cowboy-hat", "buckle-collar-corset", "punk-stud-wristbands", "wolf-pack-boots"] },
      { id: "look-03", img: "img/look-03.jpg", title: "LOOKS CAN KILL", time: "01:12", place: "car park, bay 13",
        quote: "flash on, feelings off", note: "Studded cross top, camo cap, fishnets and a chain that could open a door.",
        pieces: ["holy-studs-top", "badge-captain-cap", "crucifix-layer-necklace", "pyramid-cross-ring"] },
      { id: "look-04", img: "img/look-04.jpg", title: "SOURCE CODE", time: "02:05", place: "old town, wall no. 4",
        quote: "compiled at 2am", note: "Cropped leather, a white tank and denim so wide it has its own weather.",
        pieces: ["washed-out-biker", "sweetest-girls-tank", "swirl-tattoo-jeans", "holy-cross-bag"] },
      { id: "look-05", img: "img/look-05.jpg", title: "MIND THE GAP", time: "02:48", place: "last train, platform 2",
        quote: "missed it on purpose", note: "Fur hood up, belted micro shorts, sheer tights and chunky platforms.",
        pieces: ["fur-real-jacket", "buckle-up-shorts", "tank-platform-boots", "studded-bandana-headband"] },
      { id: "look-06", img: "img/look-06.jpg", title: "BLOWN AWAY", time: "03:30", place: "corner of nowhere st.",
        quote: "home is a rumour", note: "Camo under shaggy fur, leather micro shorts and a belt bag full of secrets.",
        pieces: ["afghan-shag-coat", "chain-fur-shorts", "diva-leopard-chain-belt", "skull-crush-clip"] }
    ]
  };

  window.CD_PRODUCTS = [
    /* ---------------- DROP #004 ---------------- */
    { id: "leather-error-corset", code: "0401", name: "Leather Error Corset Top", price: 68, cat: "corsets", img: "img/drop-01.jpg", tag: "NEW", drop: "004", added: 13, sizes: CLOTHES, color: "Black", focus: [50, 50],
      desc: "High-neck faux leather corset with a stitched rosary and cross appliqué, boned panels and lace-up sides. Looks like a system error, fits like a secret.",
      details: ["Faux leather, lined", "Lace-up sides to adjust the fit", "Hidden back zip", "Fitted, cropped at the hip"] },
    { id: "ripped-af-jeans", code: "0402", name: "Ripped.AF Low-Rise Jeans", price: 94, cat: "bottoms", img: "img/drop-02.jpg", tag: "LOW STOCK", hot: true, drop: "004", added: 12, sizes: CLOTHES, color: "Washed black", focus: [55, 50],
      desc: "Low-rise washed black denim laced from hip to hem with silver eyelets and long cords you can tie however you want.",
      details: ["Heavy cotton denim", "Silver eyelets + cotton laces", "Low rise, slim flare leg", "Wash inside out, cold"] },
    { id: "angel-wing-tee", code: "0403", name: "Angel Wing Baby Tee", price: 39, cat: "tops", img: "img/drop-03.jpg", tag: "NEW", drop: "004", added: 11, sizes: CLOTHES, color: "Black", focus: [42, 55],
      desc: "Black baby tee with hand-set rhinestone wings across the back. Plain in front, angelic when you walk away.",
      details: ["Cotton-stretch jersey", "Rhinestone wings on the back", "Slim, slightly cropped", "Hand wash, don't tumble dry"] },
    { id: "skull-kiss-knit", code: "0404", name: "Skull Kiss Oversized Knit", price: 112, cat: "knitwear", img: "img/drop-04.jpg", tag: "BESTSELLER", drop: "004", added: 10, sizes: CLOTHES, color: "Faded black", focus: [45, 50],
      desc: "Oversized open-knit jumper with laddered holes and raw edges. Throw it over anything and look like you just walked out of a basement show.",
      details: ["Loose-gauge acrylic-wool knit", "Distressed by hand — every piece is different", "Oversized, dropped shoulders", "Hand wash, dry flat"] },
    { id: "chrome-heart-skirt", code: "0405", name: "Chrome Heart Mini Skirt", price: 72, cat: "bottoms", img: "img/drop-05.jpg", tag: "NEW", drop: "004", added: 9, sizes: CLOTHES, color: "Grey wash", focus: [50, 45],
      desc: "Grey-washed denim micro skirt with a pleated frill, printed crosses and crowns, grommets and ribbon lace-ups on both sides.",
      details: ["Cotton denim", "Ribbon lace-up sides", "Raw frayed hem", "Low rise, micro length"] },
    { id: "midnight-fiction-slip", code: "0406", name: "Midnight Fiction Slip Dress", price: 89, cat: "dresses", img: "img/drop-06.jpg", tag: "NEW", drop: "004", added: 8, sizes: CLOTHES, color: "Heather grey", focus: [52, 45],
      desc: "Sweetheart mini dress in soft jersey with ruched cups and patch pockets. Wear it alone or over baggy jeans like it's 2003.",
      details: ["Cotton jersey", "Ruched sweetheart neckline", "Adjustable straps", "Mini length"] },
    { id: "glitch-platform-boots", code: "0407", name: "Glitch Platform Boots", price: 159, cat: "shoes", img: "img/drop-07.jpg", tag: "LAST 3", hot: true, drop: "004", added: 7, sizes: SHOES, color: "Black", focus: [45, 45],
      desc: "Thigh-high faux leather boots on a chunky platform with full lace-up front and side zip.",
      details: ["Faux leather", "12 cm heel / 6 cm platform", "Side zip + lace-up front", "True to size"] },
    { id: "bow-exe-warmers", code: "0408", name: "Bow.exe Arm Warmers", price: 29, cat: "accessories", img: "img/drop-08.jpg", tag: "NEW", drop: "004", added: 6, sizes: ONE, color: "Black", focus: [50, 50],
      desc: "Long lace arm warmers with a ribbed knit cuff, thumb hole and satin ribbons wrapped up the arm.",
      details: ["Stretch lace + rib knit", "Satin ribbon ties", "Thumb hole", "One size"] },

    /* ---------------- DROP #003 · HAZARDOUS ---------------- */
    { id: "star-girl-earrings", code: "0005", name: "Rhinestone Star Earrings", price: 25, cat: "accessories", img: "img/anatomy-earrings.jpg", drop: "003", added: 5, sizes: ONE, color: "Silver", focus: [50, 50],
      desc: "Oversized open-star drop earrings paved with clear rhinestones. Catch every flash in the club.",
      details: ["Silver-tone metal", "Clear rhinestones", "Hook fastening", "Approx. 7 cm"] },
    { id: "holy-studs-top", code: "0012", name: "Holy Studs Cross Top", price: 45, cat: "tops", img: "img/anatomy-top.jpg", tag: "BESTSELLER", drop: "003", added: 4, sizes: CLOTHES, color: "White", focus: [50, 45],
      desc: "Fitted white tee with a pyramid-stud cross across the front and a strappy open back.",
      details: ["Cotton-stretch jersey", "Metal pyramid studs", "Strappy cut-out back", "Slim fit"] },
    { id: "fur-real-jacket", code: "0022", name: "Fur Real Leather Jacket", price: 189, cat: "outerwear", img: "img/anatomy-jacket.jpg", drop: "003", added: 3, sizes: CLOTHES, color: "Black / camel fur", focus: [50, 45],
      desc: "Cropped padded jacket with a faux fur hood and ribbed striped cuffs. Warm enough for the smoking area.",
      details: ["Faux leather shell, padded", "Removable faux fur trim", "Ribbed knit cuffs and hem", "Boxy, cropped"] },
    { id: "buckle-up-shorts", code: "0038", name: "Buckle Up Leather Shorts", price: 69, cat: "bottoms", img: "img/anatomy-shorts.jpg", drop: "003", added: 2, sizes: CLOTHES, color: "Black", focus: [50, 45],
      desc: "Low-rise faux leather micro shorts with an oversized studded fold-over belt and a chunky square buckle.",
      details: ["Faux leather", "Detachable studded belt", "Low rise", "Wipe clean"] },
    { id: "stomp-buckle-boots", code: "0047", name: "Stomp Buckle Wrap Boots", price: 149, cat: "shoes", img: "img/anatomy-boots.jpg", tag: "LOW STOCK", hot: true, drop: "003", added: 1, sizes: SHOES, color: "Black", focus: [50, 50],
      desc: "Slouchy fold-over wedge boots wrapped in eyelet straps with silver buckles and a pointed toe.",
      details: ["Faux leather", "Hidden 9 cm wedge", "Adjustable buckle straps", "Pointed toe"] },

    /* ---------------- TOPS ---------------- */
    { id: "crucifix-studded-corset", code: "T03", name: "Crucifix Studded Corset", price: 98, cat: "tops", img: "img/tops/top-03.jpg", tag: "NEW", drop: "005", added: 33, sizes: CLOTHES, color: "Black", focus: [55, 62],
      desc: "Overbust corset in glossy black faux leather with steel boning, silver studs down every seam and a studded cross on the bust.",
      details: ["Faux leather, cotton lining", "Steel boning", "Silver studs + studded cross", "Back lace-up to cinch the waist"] },
    { id: "stardust-cowl-halter", code: "T04", name: "Stardust Cowl Halter", price: 46, cat: "tops", img: "img/tops/top-04.jpg", drop: "005", added: 32, sizes: CLOTHES, color: "Bronze glitter", focus: [50, 55],
      desc: "Sheer bronze-glitter halter with a deep draped cowl front. Layer it over a metallic bra top and let it swing.",
      details: ["Lurex mesh knit", "Deep cowl neckline", "Thin halter straps", "Loose, hip length"] },
    { id: "cathedral-lace-cami", code: "T05", name: "Cathedral Lace Cami", price: 52, cat: "tops", img: "img/tops/top-05.jpg", tag: "BESTSELLER", drop: "005", added: 31, sizes: CLOTHES, color: "Black", focus: [38, 68],
      desc: "Long sheer cami in floral black lace with a triangle bra and a thin waist seam. Wear it over shorts like a mini dress.",
      details: ["Stretch lace", "Triangle cups", "Adjustable straps", "Long line — covers the hips"] },
    { id: "night-racer-baby-tee", code: "T06", name: "Night Racer Baby Tee", price: 35, cat: "tops", img: "img/tops/top-06.jpg", tag: "NEW", drop: "005", added: 30, sizes: CLOTHES, color: "White", focus: [48, 36],
      desc: "Shrunken white baby tee with a gothic-script racing graphic in cracked black print.",
      details: ["100% cotton", "Cracked-effect print", "Cropped, slim fit", "Wash inside out"] },
    { id: "safety-pin-slashed-tank", code: "T07", name: "Safety Pin Slashed Tank", price: 32, cat: "tops", img: "img/tops/top-07.jpg", drop: "005", added: 29, sizes: CLOTHES, color: "Black", focus: [42, 55],
      desc: "Black jersey tank slashed at the neckline and held together with silver safety pins. Raw-cut hem, no rules.",
      details: ["Cotton jersey", "Hand-slashed neckline", "Silver safety pins", "Raw hem"] },
    { id: "bad-angel-tube", code: "T08", name: "Bad Angel Tube Top", price: 28, cat: "tops", img: "img/tops/top-08.jpg", drop: "005", added: 28, sizes: CLOTHES, color: "Off-white", focus: [48, 68],
      desc: "Simple off-white tube top in thick stretch jersey. Let your black lace bra peek over the top.",
      details: ["Cotton-stretch jersey", "Silicone grip inside", "Strapless", "Cropped"] },
    { id: "wild-thing-halter", code: "T09", name: "Wild Thing O-Ring Halter", price: 42, cat: "tops", img: "img/tops/top-09.jpg", tag: "NEW", drop: "005", added: 27, sizes: CLOTHES, color: "Leopard", focus: [56, 55],
      desc: "Leopard-print bandeau with a keyhole and a chunky O-ring chain halter neck.",
      details: ["Stretch mesh, lined", "Metal O-ring chain halter", "Keyhole front", "Cropped"] },
    { id: "pinstripe-prefect-shirt", code: "T10", name: "Pinstripe Prefect Shirt", price: 64, cat: "tops", img: "img/tops/top-10.jpg", drop: "005", added: 26, sizes: CLOTHES, color: "Black pinstripe", focus: [38, 30],
      desc: "Nipped-in black pinstripe shirt with gold buttons and shoulder epaulettes. Headmistress, but make it afterparty. Leopard tie not included.",
      details: ["Poly-viscose suiting", "Gold-tone buttons", "Fitted waist, cropped sleeves", "Dry clean"] },
    { id: "molten-metal-halter", code: "T11", name: "Molten Metal Halter Cami", price: 48, cat: "tops", img: "img/tops/top-11.jpg", drop: "005", added: 25, sizes: CLOTHES, color: "Bronze foil", focus: [50, 35],
      desc: "Liquid bronze foil halter cami with a V neck and a ruched centre front. Shines under every light.",
      details: ["Foil-coated stretch jersey", "Halter neck, open back", "Ruched front", "Slim, cropped"] },
    { id: "bleached-rockstar-tee", code: "T12", name: "Bleached Rockstar Tee", price: 38, cat: "tops", img: "img/tops/top-12.jpg", tag: "LOW STOCK", hot: true, drop: "005", added: 24, sizes: CLOTHES, color: "Bleached black", focus: [45, 40],
      desc: "Vintage-feel band-style tee, bleached, cut off the shoulder and shredded at the hem. Every piece is hand-finished so no two are the same.",
      details: ["100% cotton", "Hand-bleached print", "Off-shoulder cut", "Distressed hem"] },
    { id: "liquid-silver-fringe", code: "T13", name: "Liquid Silver Fringe Top", price: 58, cat: "tops", img: "img/tops/top-13.jpg", tag: "NEW", drop: "005", added: 23, sizes: CLOTHES, color: "Silver", focus: [40, 62],
      desc: "Sleeveless crop top made of cascading silver fringe that moves like liquid metal. Wear a black bra underneath.",
      details: ["Metallic yarn fringe", "Sheer mesh base", "Cropped", "Hand wash only"] },
    { id: "skull-studs-rib-tank", code: "T14", name: "Skull & Studs Rib Tank", price: 36, cat: "tops", img: "img/tops/top-14.jpg", tag: "BESTSELLER", drop: "005", added: 22, sizes: CLOTHES, color: "Black", focus: [45, 40],
      desc: "Black ribbed tank with silver studs along the straps and neckline and an embroidered skull patch.",
      details: ["Cotton rib jersey", "Silver dome studs", "Embroidered skull", "Slim fit"] },
    { id: "off-duty-slouch-knit", code: "T15", name: "Off-Duty Slouch Knit", price: 72, cat: "tops", img: "img/tops/top-15.jpg", drop: "005", added: 21, sizes: CLOTHES, color: "Charcoal", focus: [50, 55],
      desc: "Chunky charcoal knit with a wide off-shoulder neckline, batwing sleeves and a deep ribbed waistband.",
      details: ["Wool-blend chunky knit", "Off-shoulder neckline", "Batwing sleeves", "Relaxed, hip length"] },
    { id: "rebel-print-slouch-tee", code: "T16", name: "Rebel Print Slouch Tee", price: 34, cat: "tops", img: "img/tops/top-16.jpg", drop: "005", added: 20, sizes: CLOTHES, color: "White", focus: [50, 50],
      desc: "Oversized white tee with a faded photo print and slogan text. Wear it falling off one shoulder.",
      details: ["100% cotton", "Faded screen print", "Oversized fit", "Wide neckline"] },
    { id: "snake-charmer-rib-tank", code: "T17", name: "Snake Charmer Rib Tank", price: 34, cat: "tops", img: "img/tops/top-17.jpg", tag: "NEW", drop: "005", added: 19, sizes: CLOTHES, color: "Grey snake", focus: [58, 52],
      desc: "Scoop-neck ribbed tank in a smudged grey snakeskin print with a flocked logo across the chest.",
      details: ["Cotton rib jersey", "All-over snake print", "Flocked chest print", "Body-hugging fit"] },
    { id: "snow-leopard-tube", code: "T18", name: "Snow Leopard Rhinestone Tube", price: 54, cat: "tops", img: "img/tops/top-18.jpg", tag: "NEW", drop: "005", added: 18, sizes: CLOTHES, color: "White / snow leopard", focus: [52, 67],
      desc: "White corset-style tube top with a snow-leopard faux fur trim, rhinestone script and grommet detail at the hem.",
      details: ["Stretch twill, lined", "Faux fur trim", "Rhinestone graphic", "Back zip"] },
    { id: "leopard-halter-bandeau", code: "T19", name: "Leopard Halter Bandeau", price: 38, cat: "tops", img: "img/tops/top-19.jpg", drop: "005", added: 17, sizes: CLOTHES, color: "Leopard / white", focus: [55, 65],
      desc: "Leopard bandeau with contrast white binding and a halter tie that loops through a silver ring.",
      details: ["Stretch jersey", "Contrast binding", "Halter tie with ring", "Cropped"] },
    { id: "swirl-girl-halter", code: "T20", name: "Swirl Girl Halter Top", price: 39, cat: "tops", img: "img/tops/top-20.jpg", drop: "005", added: 16, sizes: CLOTHES, color: "White / black print", focus: [38, 55],
      desc: "Very 2004: white strapless top with black swirl-and-flower print and a striped halter scarf tie.",
      details: ["Stretch cotton", "Printed swirl graphic", "Striped halter tie", "Cropped, fitted"] },
    { id: "rhinestone-riot-tee", code: "T21", name: "Rhinestone Riot Off-Shoulder Tee", price: 44, cat: "tops", img: "img/tops/top-21.jpg", tag: "LOW STOCK", hot: true, drop: "005", added: 15, sizes: CLOTHES, color: "Black", focus: [45, 55],
      desc: "Black off-shoulder tee with a rhinestone gothic logo that sparkles under flash.",
      details: ["Cotton-stretch jersey", "Hot-fix rhinestones", "Off-shoulder cut", "Slim fit"] },
    { id: "stripe-layer-longsleeve", code: "T22", name: "Stripe Layer Longsleeve", price: 42, cat: "tops", img: "img/tops/top-22.jpg", drop: "005", added: 14, sizes: CLOTHES, color: "Black / white stripe", focus: [55, 55],
      desc: "Black-and-white striped longsleeve with a black short-sleeve layer on top. One piece, looks like two.",
      details: ["Cotton jersey", "Mock-layer construction", "Long fitted sleeves", "Hip length"] },

    /* ---------------- TOPS (new) ---------------- */
    { id: "varsity-halter-corset", code: "T23", name: "Varsity Halter Corset Top", price: 58, cat: "tops", img: "img/tops/top-23.jpg", tag: "NEW", drop: "005", added: 35, sizes: CLOTHES, color: "Washed black", focus: [45, 50],
      desc: "Black halter corset top with sporty piping, varsity number and patch prints and a lace-up back. Sports bar, but make it gothic.",
      details: ["Cotton twill, lined", "Printed varsity patches", "Halter neck, lace-up back", "Fitted, hip length"] },
    { id: "sweetest-girls-tank", code: "T24", name: "Sweetest Girls Tank", price: 32, cat: "tops", img: "img/tops/top-24.jpg", drop: "005", added: 34, sizes: CLOTHES, color: "White", focus: [42, 48],
      desc: "White scoop tank with a faded photo print and a “GIRLS / sweetest” slogan. Layer it under an open-knit cardigan.",
      details: ["Cotton rib jersey", "Vintage-effect print", "Scoop neck", "Slim fit"] },

    /* ---------------- CORSETS ---------------- */
    { id: "leopard-lace-bustier", code: "C02", name: "Leopard Lace Bustier", price: 76, cat: "corsets", img: "img/corset/corset-02.jpg", tag: "NEW", drop: "005", added: 44, sizes: CLOTHES, color: "Leopard / black lace", focus: [55, 48],
      desc: "Leopard satin bustier with black lace trim, satin bows and boned panels. Pair it with a fur-trim jacket and a mini.",
      details: ["Satin, cotton lining", "Lace trim + satin bows", "Spiral steel boning", "Back lace-up"] },
    { id: "grunge-grommet-corset", code: "C03", name: "Grunge Grommet Corset", price: 84, cat: "corsets", img: "img/corset/corset-03.jpg", tag: "BESTSELLER", drop: "005", added: 43, sizes: CLOTHES, color: "Distressed black", focus: [48, 55],
      desc: "Strapless corset in cracked, washed faux leather with brass grommets and a lace-up front you can wear open or tight.",
      details: ["Distressed faux leather", "Brass grommets", "Lace-up front + side zip", "Cropped"] },
    { id: "wildcat-satin-corset", code: "C04", name: "Wildcat Satin Corset", price: 79, cat: "corsets", img: "img/corset/corset-04.jpg", tag: "NEW", drop: "005", added: 42, sizes: CLOTHES, color: "Leopard satin", focus: [58, 65],
      desc: "Leopard satin corset top with sculpted sweetheart cups and a pointed hem. Very 2003 music video.",
      details: ["Stretch satin, lined", "Moulded sweetheart cups", "Boned bodice", "Back zip"] },
    { id: "peekaboo-mesh-corset", code: "C05", name: "Peekaboo Mesh Corset", price: 62, cat: "corsets", img: "img/corset/corset-05.jpg", drop: "005", added: 41, sizes: CLOTHES, color: "Black", focus: [43, 55],
      desc: "Black corset with a sheer mesh centre panel, hook-and-eye front and thin straps. Shows just enough.",
      details: ["Satin + sheer mesh", "Hook-and-eye front", "Adjustable straps", "Cropped, fitted"] },
    { id: "chain-reaction-corset", code: "C06", name: "Chain Reaction Zip Corset", price: 88, cat: "corsets", img: "img/corset/corset-06.jpg", tag: "LOW STOCK", hot: true, drop: "005", added: 40, sizes: CLOTHES, color: "Black", focus: [42, 55],
      desc: "Underbust zip-front corset with silver chains draped across the waist. Wear it over a cami or with the matching shrug.",
      details: ["Cotton twill, boned", "Front zip", "Detachable silver chains", "Underbust"] },
    { id: "lasercut-longsleeve-corset", code: "C07", name: "Lasercut Longsleeve Corset", price: 96, cat: "corsets", img: "img/corset/corset-07.jpg", drop: "005", added: 39, sizes: CLOTHES, color: "Black", focus: [55, 65],
      desc: "Long-sleeve corset bodysuit in laser-cut faux leather with a plunging sweetheart neckline. Office siren after midnight.",
      details: ["Laser-cut faux leather", "Stretch mesh lining", "Long sleeves", "Back zip"] },
    { id: "buckle-collar-corset", code: "C08", name: "Buckle Collar Moto Corset", price: 92, cat: "corsets", img: "img/corset/corset-08.jpg", tag: "NEW", drop: "005", added: 38, sizes: CLOTHES, color: "Black", focus: [45, 55],
      desc: "High-neck faux leather corset with a zip front and three eyelet buckle straps across the collar. Matching cuffs sold separately.",
      details: ["Faux leather", "Buckle strap collar", "Two-way front zip", "Cropped"] },
    { id: "vampira-lace-corset", code: "C09", name: "Vampira Red Lace Corset", price: 74, cat: "corsets", img: "img/corset/corset-09.jpg", tag: "NEW", drop: "005", added: 37, sizes: CLOTHES, color: "Blood red", focus: [45, 62],
      desc: "Blood-red lace and mesh corset with white lace cups, satin bows and long ribbon ties. For girls who bite.",
      details: ["Stretch lace + mesh", "Satin ribbon ties", "Boned bodice", "Back lace-up"] },
    { id: "worn-leather-bustier", code: "C10", name: "Worn Leather Bustier", price: 86, cat: "corsets", img: "img/corset/corset-10.jpg", drop: "005", added: 36, sizes: CLOTHES, color: "Washed brown-black", focus: [52, 70],
      desc: "Strapless bustier in heavily worn, sanded faux leather with panel seams and eyelets. Looks like it's been to a hundred shows.",
      details: ["Sanded faux leather", "Seam-panel bodice", "Silver eyelets", "Back zip"] },

    /* ---------------- BOTTOMS ---------------- */
    { id: "smoke-sheer-flares", code: "B04", name: "Smoke Sheer Flare Pants", price: 68, cat: "bottoms", img: "img/bottoms/bottom-04.jpg", tag: "NEW", drop: "005", added: 56, sizes: CLOTHES, color: "Black flock", focus: [45, 68],
      desc: "Sheer black flared trousers with a smoky flocked print. Wear them over a bodysuit or layered with a chiffon apron skirt like a ghost bride.",
      details: ["Sheer flocked mesh", "Elastic high-rise waist", "Wide flared leg", "Hand wash, cold"] },
    { id: "swirl-tattoo-jeans", code: "B05", name: "Swirl Tattoo Baggy Jeans", price: 82, cat: "bottoms", img: "img/bottoms/bottom-05.jpg", tag: "BESTSELLER", drop: "005", added: 55, sizes: CLOTHES, color: "Grey wash", focus: [58, 70],
      desc: "Baggy grey-wash jeans with a white tribal swirl embroidered down one leg. Pairs with chunky white sneakers and nothing to prove.",
      details: ["Heavy cotton denim", "White swirl embroidery", "Low rise, baggy leg", "Wash inside out"] },
    { id: "mocha-cargo-lowrise", code: "B06", name: "Mocha Cargo Low-Rise Pants", price: 74, cat: "bottoms", img: "img/bottoms/bottom-06.jpg", drop: "005", added: 54, sizes: CLOTHES, color: "Mocha brown", focus: [22, 85],
      desc: "Super low-rise skinny cargos in mocha brushed twill with metal button flaps and zip pockets.",
      details: ["Stretch cotton twill", "Button-flap cargo pockets", "Ultra low rise", "Skinny leg"] },
    { id: "laced-up-flare-jeans", code: "B07", name: "Laced Up Flare Jeans", price: 98, cat: "bottoms", img: "img/bottoms/bottom-07.jpg", tag: "LOW STOCK", hot: true, drop: "005", added: 53, sizes: CLOTHES, color: "Washed black", focus: [22, 75],
      desc: "Black flared jeans slashed open down both sides and laced back together with frayed denim cord. Criss-cross back waistband included.",
      details: ["Cotton denim", "Hand-frayed lace-up panels", "Low rise, flared leg", "Wash inside out, cold"] },
    { id: "leopard-rara-mini", code: "B08", name: "Leopard Ra-Ra Mini", price: 46, cat: "bottoms", img: "img/bottoms/bottom-08.jpg", tag: "NEW", drop: "005", added: 52, sizes: CLOTHES, color: "Leopard", focus: [40, 60],
      desc: "Flippy leopard ra-ra mini with a wide black fold-over waistband. Leg warmers strongly encouraged.",
      details: ["Stretch chiffon, lined", "Fold-over jersey waistband", "Tiered ruffle hem", "Micro length"] },
    { id: "frayed-denim-micro", code: "B09", name: "Frayed Denim Micro Skirt", price: 44, cat: "bottoms", img: "img/bottoms/bottom-09.jpg", drop: "005", added: 51, sizes: CLOTHES, color: "Light wash", focus: [48, 50],
      desc: "Light-wash denim micro skirt with a long frayed hem. Add a leopard belt and platform wedges and you're in 2006.",
      details: ["Cotton denim", "Raw frayed hem", "Low rise", "Micro length"] },
    { id: "chain-fur-shorts", code: "B10", name: "Chain Fur-Trim Shorts", price: 72, cat: "bottoms", img: "img/bottoms/bottom-10.jpg", tag: "NEW", drop: "005", added: 50, sizes: CLOTHES, color: "Black / sand fur", focus: [52, 58],
      desc: "Faux leather micro shorts with a shaggy faux fur hem, chain belt and hanging charms. Tribal princess energy.",
      details: ["Faux leather", "Faux fur trim", "Detachable chain belt", "Low rise"] },
    { id: "yeti-flare-jeans", code: "B11", name: "Yeti Flare Jeans", price: 108, cat: "bottoms", img: "img/bottoms/bottom-11.jpg", tag: "NEW", drop: "005", added: 49, sizes: CLOTHES, color: "Mud wash", focus: [50, 60],
      desc: "Mud-wash flared jeans with detachable shaggy faux fur cuffs and a leopard tail belt. Yes, the tail comes too.",
      details: ["Washed cotton denim", "Detachable faux fur cuffs", "Leopard tail belt included", "Low rise, flared"] },
    { id: "fur-hem-denim-mini", code: "B12", name: "Fur Hem Denim Mini", price: 58, cat: "bottoms", img: "img/bottoms/bottom-12.jpg", tag: "BESTSELLER", drop: "005", added: 48, sizes: CLOTHES, color: "Dark wash / leopard", focus: [48, 55],
      desc: "Dark-wash denim mini finished with a fluffy leopard faux fur hem and a heart charm on the belt loop.",
      details: ["Cotton denim", "Leopard faux fur hem", "Heart charm", "Low rise, mini"] },
    { id: "gold-rush-flares", code: "B13", name: "Gold Rush Flare Jeans", price: 96, cat: "bottoms", img: "img/bottoms/bottom-13.jpg", drop: "005", added: 47, sizes: CLOTHES, color: "Gold-splatter wash", focus: [55, 70],
      desc: "Distressed flare jeans splattered with gold paint, with leopard-print patches and ripped knees.",
      details: ["Cotton denim", "Hand-painted gold splatter", "Leopard patches", "Flared leg"] },
    { id: "shredded-gyaru-jeans", code: "B14", name: "Shredded Gyaru Jeans", price: 88, cat: "bottoms", img: "img/bottoms/bottom-14.jpg", tag: "LOW STOCK", hot: true, drop: "005", added: 46, sizes: CLOTHES, color: "Dirty wash", focus: [30, 80],
      desc: "Dirty-wash jeans shredded from thigh to ankle with gold paint marks. Shibuya 2005, pure chaos.",
      details: ["Cotton denim", "Hand-shredded", "Gold paint details", "Low rise, bootcut"] },
    { id: "gilded-bootcut-jeans", code: "B15", name: "Gilded Bootcut Jeans", price: 86, cat: "bottoms", img: "img/bottoms/bottom-15.jpg", drop: "005", added: 45, sizes: CLOTHES, color: "Gold-foil wash", focus: [40, 65],
      desc: "Low-rise bootcut jeans with a gold-foil fade on the thighs and knees and a whiskered wash. Heels mandatory.",
      details: ["Stretch cotton denim", "Gold foil print", "Low rise", "Bootcut leg"] },
    /* ---------------- CORE COLLECTION — always available ---------------- */
    { id: "velvet-leopard-dress", code: "D02", name: "Velvet Leopard Trim Dress", price: 92, cat: "dresses", img: "img/dresses/dress-02.jpg", tag: "BESTSELLER", drop: "core", added: 0, sizes: CLOTHES, color: "Black velvet / leopard", focus: [56, 42],
      desc: "Black velvet bustier mini dress with a bubble skirt, gold zips and leopard faux fur trim on the neckline, belt and hem.",
      details: ["Stretch velvet, lined", "Faux fur trim", "Detachable belt", "Mini length"] },
    { id: "patent-pleat-mini", code: "D03", name: "Patent Pleat Mini Dress", price: 88, cat: "dresses", img: "img/dresses/dress-03.jpg", tag: "LOW STOCK", hot: true, drop: "core", added: -1, sizes: CLOTHES, color: "Black patent", focus: [58, 62],
      desc: "High-neck sleeveless mini in glossy black patent with a flippy pleated skirt. Add a belt with attitude.",
      details: ["Patent PU, stretch lining", "Mock neck", "Pleated skirt", "Back zip"] },
    { id: "halter-babydoll-mini", code: "D04", name: "Halter Babydoll Mini", price: 49, cat: "dresses", img: "img/dresses/dress-04.jpg", drop: "core", added: -2, sizes: CLOTHES, color: "Black", focus: [49, 47],
      desc: "Floaty black halter babydoll that barely covers the essentials. Fringe boots are the only correct shoe.",
      details: ["Soft jersey", "Halter neck", "Loose babydoll shape", "Micro length"] },
    { id: "rhinestone-slogan-bodycon", code: "D05", name: "Rhinestone Slogan Bodycon", price: 78, cat: "dresses", img: "img/dresses/dress-05.jpg", tag: "BESTSELLER", drop: "core", added: -3, sizes: CLOTHES, color: "Black / crystal", focus: [45, 62],
      desc: "Strappy black bodycon covered in a giant rhinestone slogan. Wear it with suspenders and zero apologies.",
      details: ["Stretch jersey", "Hot-fix rhinestone text", "Thin adjustable straps", "Bodycon, mini"] },
    { id: "tinsel-streamer-dress", code: "D06", name: "Tinsel Streamer Mini Dress", price: 86, cat: "dresses", img: "img/dresses/dress-06.jpg", drop: "core", added: -4, sizes: CLOTHES, color: "Black / silver", focus: [30, 60],
      desc: "Black mini dress hung with silver lamé streamers, a ruched metallic bust and a beaded fringe hem. Moves like a disco ball.",
      details: ["Jersey + lamé", "Streamer panels", "Beaded fringe hem", "Mini length"] },
    { id: "cowl-drape-halter-dress", code: "D07", name: "Cowl Drape Halter Dress", price: 64, cat: "dresses", img: "img/dresses/dress-07.jpg", drop: "core", added: -5, sizes: CLOTHES, color: "Ash grey / black", focus: [50, 40],
      desc: "Slinky halter mini with a deep draped cowl front and open back. Comes in ash grey and black.",
      details: ["Viscose jersey", "Deep cowl neck", "Open back", "Mini length"] },
    { id: "slouch-sweater-dress", code: "D08", name: "Slouch Off-Shoulder Sweat Dress", price: 58, cat: "dresses", img: "img/dresses/dress-08.jpg", drop: "core", added: -6, sizes: CLOTHES, color: "Heather grey", focus: [40, 38],
      desc: "Oversized off-shoulder sweatshirt dress with batwing sleeves and a fitted hem. Belt it low.",
      details: ["Soft cotton fleece", "Off-shoulder neckline", "Batwing sleeves", "Mini length"] },
    { id: "disco-crystal-mini", code: "D09", name: "Disco Crystal Mesh Mini", price: 129, cat: "dresses", img: "img/dresses/dress-09.jpg", tag: "LAST 2", hot: true, drop: "core", added: -7, sizes: CLOTHES, color: "Silver crystal", focus: [50, 52],
      desc: "Scoop-neck mini dress made entirely of crystal mesh. Throw a fur over it and go.",
      details: ["Crystal chainmail mesh", "Stretch lining", "Scoop neck", "Mini length"] },
    { id: "open-back-halter-mini", code: "D10", name: "Open Back Halter Mini", price: 54, cat: "dresses", img: "img/dresses/dress-10.jpg", drop: "core", added: -8, sizes: CLOTHES, color: "White", focus: [40, 35],
      desc: "High-neck white halter mini with a completely open back and side cut-outs. Brown suede boots, trust us.",
      details: ["Stretch jersey", "High halter neck", "Open back", "Micro length"] },
    { id: "butterfly-chain-dress", code: "D11", name: "Butterfly Chain Backless Dress", price: 118, cat: "dresses", img: "img/dresses/dress-11.jpg", drop: "core", added: -9, sizes: CLOTHES, color: "Mocha", focus: [55, 50],
      desc: "Mocha off-shoulder mini with angel sleeves, a fully open back strung with beaded chains and a gold sequin butterfly at the waist.",
      details: ["Satin jersey", "Beaded back chains", "Sequin butterfly", "Mini length"] },
    { id: "serpent-mesh-maxi", code: "D12", name: "Serpent Mesh Cut-Out Maxi", price: 96, cat: "dresses", img: "img/dresses/dress-12.jpg", tag: "BESTSELLER", drop: "core", added: -10, sizes: CLOTHES, color: "Smoke print", focus: [50, 60],
      desc: "Printed mesh maxi dress with a lace-trimmed heart cut-out, halter neck and a mermaid hem.",
      details: ["Printed stretch mesh", "Lace trim", "Halter tie neck", "Maxi length"] },
    { id: "snow-leopard-halter-dress", code: "D13", name: "Snow Leopard Ruffle Dress", price: 72, cat: "dresses", img: "img/dresses/dress-13.jpg", drop: "core", added: -11, sizes: CLOTHES, color: "Snow leopard", focus: [40, 62],
      desc: "Cowl-neck halter dress in snow leopard print with tiered ruffles and a studded belt. Very Harajuku 2007.",
      details: ["Chiffon, lined", "Cowl halter neck", "Tiered ruffle skirt", "Belt included"] },
    { id: "coven-vneck-knit", code: "K02", name: "Coven V-Neck Oversized Knit", price: 79, cat: "knitwear", img: "img/knitwear/knit-02.jpg", tag: "BESTSELLER", drop: "core", added: -12, sizes: CLOTHES, color: "Black", focus: [50, 45],
      desc: "Huge black V-neck jumper in a chunky rib. Rosaries and lace flares strongly implied.",
      details: ["Chunky acrylic-wool rib", "Deep V neck", "Dropped shoulders", "Oversized"] },
    { id: "ghost-lace-knit", code: "K03", name: "Ghost Lace Open Knit", price: 84, cat: "knitwear", img: "img/knitwear/knit-03.jpg", drop: "core", added: -13, sizes: CLOTHES, color: "Ecru", focus: [40, 40],
      desc: "Ecru open-knit jumper with pointelle lace ladders and long bell sleeves. Victorian ghost, but make it cosy.",
      details: ["Cotton-blend open knit", "Bell sleeves", "Raw hem", "Relaxed fit"] },
    { id: "chainmail-cross-knit", code: "K04", name: "Chainmail Cross Knit", price: 98, cat: "knitwear", img: "img/knitwear/knit-04.jpg", tag: "LOW STOCK", hot: true, drop: "core", added: -14, sizes: CLOTHES, color: "Black / silver", focus: [55, 40],
      desc: "Black cold-shoulder knit with a chainmail-sequin cross panel on the front and a zip detail.",
      details: ["Wool-blend knit", "Metal sequin cross panel", "Cold-shoulder cut", "Relaxed fit"] },
    { id: "angel-fluff-knit", code: "K05", name: "Angel Fluff Off-Shoulder Knit", price: 86, cat: "knitwear", img: "img/knitwear/knit-05.jpg", drop: "core", added: -15, sizes: CLOTHES, color: "Cream", focus: [32, 40],
      desc: "Fluffy cream mohair-feel jumper with a fold-over off-shoulder neckline. Soft enough to sleep in.",
      details: ["Brushed mohair-blend", "Fold-over neckline", "Balloon sleeves", "Cropped, relaxed"] },
    { id: "ribcage-hooded-knit", code: "K06", name: "Ribcage Hooded Knit", price: 159, cat: "knitwear", img: "img/knitwear/knit-06.jpg", tag: "LAST 3", hot: true, drop: "core", added: -16, sizes: CLOTHES, color: "Ecru / blood red", focus: [50, 55],
      desc: "Hand-knitted chunky hoodie with a 3D ribcage and spine knitted into the back in cream and blood red. One of our favourite things ever.",
      details: ["Hand-knitted chunky wool-blend", "3D ribcage + spine", "Oversized hood", "Made to order — ships in 2 weeks"] },
    { id: "snow-bunny-boots", code: "S02", name: "Snow Bunny Platform Boots", price: 139, cat: "shoes", img: "img/shoes/shoes-02.jpg", drop: "core", added: -17, sizes: SHOES, color: "White", focus: [50, 62],
      desc: "White satin lace-up platform boots wrapped in fluffy faux fur. Yeti princess mode.",
      details: ["Satin + faux fur", "Lace-up front", "10 cm platform", "Side zip"] },
    { id: "wolf-pack-boots", code: "S03", name: "Wolf Pack Fur Stiletto Boots", price: 168, cat: "shoes", img: "img/shoes/shoes-03.jpg", tag: "BESTSELLER", drop: "core", added: -18, sizes: SHOES, color: "Wolf grey / black", focus: [50, 50],
      desc: "Slouchy shaggy faux fur boots on a black pointed stiletto, with buckle straps and silver pentagram charms.",
      details: ["Faux fur + faux leather", "Pointed toe", "11 cm stiletto", "Removable charms"] },
    { id: "crystal-cuff-booties", code: "S04", name: "Crystal Cuff Stiletto Booties", price: 154, cat: "shoes", img: "img/shoes/shoes-04.jpg", drop: "core", added: -19, sizes: SHOES, color: "Black / crystal", focus: [80, 45],
      desc: "Pointed black stiletto booties with a wide cuff of crystal mesh at the ankle.",
      details: ["Patent upper", "Crystal mesh cuff", "10 cm stiletto", "Pointed toe"] },
    { id: "tank-platform-boots", code: "S05", name: "Tank Platform Knee Boots", price: 149, cat: "shoes", img: "img/shoes/shoes-05.jpg", tag: "BESTSELLER", drop: "core", added: -20, sizes: SHOES, color: "Black", focus: [40, 75],
      desc: "Knee-high faux leather boots on a chunky lug platform. They go with literally everything.",
      details: ["Faux leather", "7 cm lug platform", "Inside zip", "True to size"] },
    { id: "corset-thigh-boots", code: "S06", name: "Corset Lace Thigh-High Boots", price: 176, cat: "shoes", img: "img/shoes/shoes-06.jpg", tag: "LOW STOCK", hot: true, drop: "core", added: -21, sizes: SHOES, color: "Black", focus: [70, 65],
      desc: "Thigh-high faux leather boots with a corset lace-up running the full length of the leg and a slim heel.",
      details: ["Stretch faux leather", "Full-length lacing", "8 cm heel", "Back zip"] },
    { id: "spike-strap-heels", code: "S07", name: "Spike Strap Platform Heels", price: 148, cat: "shoes", img: "img/shoes/shoes-07.jpg", drop: "core", added: -22, sizes: SHOES, color: "Black / silver", focus: [40, 40],
      desc: "Towering platform stilettos with studded buckle straps across the foot. Not for walking. For standing still and looking iconic.",
      details: ["Faux leather + metal studs", "16 cm heel / 6 cm platform", "Triple buckle straps", "Pointed toe"] },
    { id: "fur-cuff-patent-boots", code: "S08", name: "Fur Cuff Patent Boots", price: 145, cat: "shoes", img: "img/shoes/shoes-08.jpg", drop: "core", added: -23, sizes: SHOES, color: "Black patent / grey fur", focus: [30, 75],
      desc: "Patent knee boots with studded seams, a silver logo zip and a fluffy faux fur cuff.",
      details: ["Patent PU", "Removable faux fur cuff", "9 cm heel", "Side zip"] },
    { id: "punk-stud-wristbands", code: "A01", name: "Punk Stud Wristband Stack", price: 39, cat: "accessories", img: "img/accessories/acc-01.jpg", tag: "BESTSELLER", drop: "core", added: -24, sizes: ONE, color: "Black / silver", focus: [22, 35],
      desc: "Set of three leather wristbands: cone studs, pyramid studs and a double buckle. Stack them, obviously.",
      details: ["Faux leather", "Metal studs", "Snap + buckle closures", "Set of 3"] },
    { id: "holy-cross-bag", code: "A02", name: "Holy Cross Studded Bag", price: 89, cat: "accessories", img: "img/accessories/acc-02.jpg", tag: "BESTSELLER", drop: "core", added: -25, sizes: ONE, color: "Black", focus: [45, 78],
      desc: "Slouchy black shoulder bag with a pyramid-stud cross, studded strap and cargo pockets.",
      details: ["Faux leather", "Pyramid studs", "Adjustable strap", "Zip closure"] },
    { id: "mermaid-pearl-necklace", code: "A03", name: "Mermaid Pearl Rope Necklace", price: 42, cat: "accessories", img: "img/accessories/acc-03.jpg", drop: "core", added: -26, sizes: ONE, color: "Pearl / brown cord", focus: [50, 45],
      desc: "Extra-long rope necklace of baroque freshwater-style pearls and shells on a suede cord. Wrap it twice.",
      details: ["Faux baroque pearls + shell", "Suede cord", "Approx. 120 cm", "Tie closure"] },
    { id: "badge-captain-cap", code: "A04", name: "Badge Captain Cap", price: 44, cat: "accessories", img: "img/accessories/acc-04.jpg", drop: "core", added: -27, sizes: ONE, color: "Black", focus: [45, 15],
      desc: "Black captain cap with a braided band and a random stack of pin badges and safety pins. No two are the same.",
      details: ["Cotton twill", "Braided band", "Assorted pin badges", "Adjustable back"] },
    { id: "leopard-pyramid-cuffs", code: "A05", name: "Leopard & Pyramid Cuff Set", price: 48, cat: "accessories", img: "img/accessories/acc-05.jpg", tag: "NEW", drop: "core", added: -28, sizes: ONE, color: "Leopard / silver", focus: [50, 75],
      desc: "Mix-and-match set of leopard bangles, a pyramid-stud cuff and a cross cutout wristband.",
      details: ["Resin + faux leather", "Pyramid studs", "Set of 5", "One size"] },
    { id: "motorway-studded-bag", code: "A06", name: "Motorway Studded Bag", price: 119, cat: "accessories", img: "img/accessories/acc-06.jpg", tag: "LOW STOCK", hot: true, drop: "core", added: -29, sizes: ONE, color: "Storm grey", focus: [40, 75],
      desc: "Soft washed-grey moto bag with round studs, buckles and braided handles. The 2006 it-bag energy.",
      details: ["Washed faux leather", "Silver studs + buckles", "Detachable strap", "Zip pocket"] },
    { id: "holy-leopard-phone-case", code: "A07", name: "Holy Leopard Phone Case", price: 32, cat: "accessories", img: "img/accessories/acc-07.jpg", drop: "core", added: -30, sizes: ONE, color: "Leopard / silver", focus: [45, 70],
      desc: "Leopard print phone case with a pyramid-stud cross down the back.",
      details: ["Shock-absorbing TPU", "Metal pyramid studs", "Most iPhone models", "Ask us for sizes"] },
    { id: "leopard-pyramid-bag", code: "A08", name: "Leopard Pyramid Stud Bag", price: 96, cat: "accessories", img: "img/accessories/acc-08.jpg", drop: "core", added: -31, sizes: ONE, color: "Leopard fur / black", focus: [50, 60],
      desc: "Faux fur leopard bowling bag with pyramid stud stripes, eyelet drawstrings and chunky handles.",
      details: ["Faux fur + faux leather", "Pyramid studs", "Eyelet drawstrings", "Zip closure"] },
    { id: "purple-rain-charm-bag", code: "A09", name: "Purple Rain Charm Bag", price: 109, cat: "accessories", img: "img/accessories/acc-09.jpg", tag: "NEW", drop: "core", added: -32, sizes: ONE, color: "Metallic purple", focus: [50, 55],
      desc: "Crinkled metallic purple moto bag, delivered with a bunch of charms and keyrings clipped on the side.",
      details: ["Metallic faux leather", "Charm set included", "Studded handles", "Zip closure"] },
    { id: "rhinestone-rodeo-belt", code: "A10", name: "Rhinestone Rodeo Belt", price: 58, cat: "accessories", img: "img/accessories/acc-10.jpg", tag: "BESTSELLER", drop: "core", added: -33, sizes: ONE, color: "Glitter white / crystal", focus: [45, 55],
      desc: "Glitter white western belt covered in crystals, with an oversized rhinestone buckle.",
      details: ["Glitter faux leather", "Crystal studs", "Western buckle", "Adjustable to 95 cm"] },
    { id: "diva-leopard-chain-belt", code: "A11", name: "Diva Leopard Chain Belt", price: 46, cat: "accessories", img: "img/accessories/acc-11.jpg", drop: "core", added: -34, sizes: ONE, color: "Leopard / crystal", focus: [50, 40],
      desc: "Skinny leopard belt spelling DIVA in rhinestone letters, with a hanging chain and crystal cross.",
      details: ["Faux leather", "Rhinestone letters", "Detachable chain + cross", "Adjustable"] },
    { id: "pyramid-cross-ring", code: "A12", name: "Pyramid Cross Double Ring", price: 28, cat: "accessories", img: "img/accessories/acc-12.jpg", drop: "core", added: -35, sizes: ONE, color: "Silver", focus: [55, 60],
      desc: "Two-finger ring shaped like a pyramid-stud cross. Punches above its weight.",
      details: ["Silver-tone metal", "Double-finger fit", "Adjustable band", "Nickel free"] },
    { id: "spiked-cowboy-hat", code: "A13", name: "Spiked Cowboy Hat", price: 69, cat: "accessories", img: "img/accessories/acc-13.jpg", tag: "NEW", drop: "core", added: -36, sizes: ONE, color: "Black / silver", focus: [30, 25],
      desc: "Black felt cowboy hat covered in silver cone spikes. Yeehaw, but goth.",
      details: ["Wool-blend felt", "Metal cone spikes", "Inner sweatband", "One size, adjustable"] },
    { id: "crucifix-layer-necklace", code: "A14", name: "Crucifix Layer Necklace Set", price: 38, cat: "accessories", img: "img/accessories/acc-14.jpg", drop: "core", added: -37, sizes: ONE, color: "Silver", focus: [45, 55],
      desc: "Three layered ball chains with a sword, a filigree cross and a clear acrylic crucifix.",
      details: ["Silver-tone chains", "Acrylic + metal pendants", "Set of 3", "Lobster clasps"] },
    { id: "tail-charm-messenger", code: "A15", name: "Tail Charm Messenger Bag", price: 79, cat: "accessories", img: "img/accessories/acc-15.jpg", drop: "core", added: -38, sizes: ONE, color: "Black", focus: [70, 50],
      desc: "Big black canvas messenger with eyelets, a chain strap, pin badges and a faux fur tail charm with a tiny skeleton.",
      details: ["Cotton canvas", "Faux fur tail + skeleton charm", "Chain + canvas strap", "Magnetic flap"] },
    { id: "leopard-kitty-charm", code: "A16", name: "Leopard Kitty Plush Charm", price: 24, cat: "accessories", img: "img/accessories/acc-16.jpg", tag: "NEW", drop: "core", added: -39, sizes: ONE, color: "Leopard / pink", focus: [30, 65],
      desc: "Fluffy leopard kitty plush with a glossy pink bow, on a silver chain clip for your bag or jeans.",
      details: ["Plush + satin bow", "Silver chain clip", "Approx. 12 cm", "Spot clean"] },
    { id: "skull-crush-clip", code: "A17", name: "Skull Crush Hair Clip", price: 14, cat: "accessories", img: "img/accessories/acc-17.jpg", drop: "core", added: -40, sizes: ONE, color: "Black / silver", focus: [55, 25],
      desc: "Black skull and crossbones hair clip with silver heart eyes.",
      details: ["Enamel metal", "Snap clip", "Approx. 6 cm", "Sold individually"] },
    { id: "pyramid-stud-phone-case", code: "A18", name: "Pyramid Stud Phone Case", price: 34, cat: "accessories", img: "img/accessories/acc-18.jpg", drop: "core", added: -41, sizes: ONE, color: "Black / silver", focus: [55, 80],
      desc: "All-over pyramid-stud phone case. Heavy, shiny, perfect.",
      details: ["Shock-absorbing TPU", "Metal pyramid studs", "Most iPhone models", "Ask us for sizes"] },
    { id: "studded-bandana-headband", code: "A19", name: "Studded Bandana Headband", price: 22, cat: "accessories", img: "img/accessories/acc-19.jpg", drop: "core", added: -42, sizes: ONE, color: "Black / silver", focus: [52, 25],
      desc: "Wide black bandana headband with silver dome studs. Instant 2004 scene kid.",
      details: ["Cotton twill", "Silver studs", "Elastic back", "One size"] },
    { id: "moto-baker-boy-cap", code: "A20", name: "Moto Buckle Baker Boy Cap", price: 49, cat: "accessories", img: "img/accessories/acc-20.jpg", drop: "core", added: -43, sizes: ONE, color: "Black", focus: [45, 20],
      desc: "Faux leather baker boy cap with an eyelet buckle strap around the band.",
      details: ["Faux leather", "Eyelet buckle strap", "Satin lining", "Adjustable"] },
    { id: "crystal-keys-phone-case", code: "A21", name: "Crystal Keys Phone Case", price: 39, cat: "accessories", img: "img/accessories/acc-21.jpg", tag: "NEW", drop: "core", added: -44, sizes: ONE, color: "Black / crystal", focus: [40, 55],
      desc: "Hand-set rhinestone phone case with a piano keyboard and music notes.",
      details: ["TPU case", "Hand-set rhinestones", "Most iPhone models", "Ask us for sizes"] },
    { id: "fallen-angel-ear-stack", code: "A22", name: "Fallen Angel Ear Stack", price: 36, cat: "accessories", img: "img/accessories/acc-22.jpg", drop: "core", added: -45, sizes: ONE, color: "Silver", focus: [35, 50],
      desc: "Set of huggie hoops with skulls, pavé crystals, spikes and a big silver angel wing drop.",
      details: ["Stainless steel", "Cubic zirconia", "Set of 6", "Hypoallergenic"] },
    { id: "skull-machine-hoop", code: "A23", name: "Skull Machine Mega Hoop", price: 34, cat: "accessories", img: "img/accessories/acc-23.jpg", drop: "core", added: -46, sizes: ONE, color: "Silver", focus: [50, 50],
      desc: "Oversized hoop earring with a mirror-cut skull machine pendant and a key charm. Sold as a single.",
      details: ["Silver-tone steel", "Mirror-cut pendant", "Approx. 9 cm", "Sold individually"] },
    { id: "cathedral-cross-earrings", code: "A24", name: "Cathedral Cross Drop Earrings", price: 29, cat: "accessories", img: "img/accessories/acc-24.jpg", tag: "BESTSELLER", drop: "core", added: -47, sizes: ONE, color: "Antique silver / pearl", focus: [40, 45],
      desc: "Ornate filigree cross drops with crystals and a tiny pearl at the tip.",
      details: ["Antique silver-tone metal", "Crystals + faux pearl", "Approx. 6 cm", "Hook fastening"] },
    /* ---------------- OUTERWEAR (core) ---------------- */
    { id: "tiger-vinyl-parka", code: "O02", name: "Tiger Lined Vinyl Parka", price: 189, cat: "outerwear", img: "img/outwear/outwear-02.jpg", tag: "NEW", drop: "core", added: -48, sizes: CLOTHES, color: "Black vinyl / tiger", focus: [55, 55],
      desc: "Oversized black vinyl bomber-parka with a tiger-print lining and a huge faux fur hood. Built for 3am in the cold.",
      details: ["Glossy vinyl shell, padded", "Tiger faux fur lining", "Detachable faux fur hood", "Oversized fit"] },
    { id: "leopard-faux-fur-coat", code: "O03", name: "Leopard Faux Fur Coat", price: 169, cat: "outerwear", img: "img/outwear/outwear-03.jpg", tag: "BESTSELLER", drop: "core", added: -49, sizes: CLOTHES, color: "Leopard", focus: [55, 50],
      desc: "Long, heavy leopard faux fur coat with a wide collar. Wear it over leather trousers and act unbothered.",
      details: ["Soft faux fur", "Satin lining", "Hook closures", "Knee length"] },
    { id: "leopard-lined-biker", code: "O04", name: "Leopard Lined Biker Jacket", price: 149, cat: "outerwear", img: "img/outwear/outwear-04.jpg", drop: "core", added: -50, sizes: CLOTHES, color: "Distressed black / leopard", focus: [45, 50],
      desc: "Crackled black faux leather jacket with a snow-leopard lining that peeks out at the cuffs, collar and hem.",
      details: ["Distressed faux leather", "Faux fur leopard lining", "Snap placket", "Slim, hip length"] },
    { id: "snake-fur-collar-jacket", code: "O05", name: "Snake Fur Collar Jacket", price: 159, cat: "outerwear", img: "img/outwear/outwear-05.jpg", tag: "LOW STOCK", hot: true, drop: "core", added: -51, sizes: CLOTHES, color: "Black snake / brown fur", focus: [50, 70],
      desc: "Black snake-embossed faux leather jacket with an oversized fluffy brown faux fur collar and cuffs.",
      details: ["Snake-embossed faux leather", "Faux fur collar + cuffs", "Zip front", "Cropped, boxy"] },
    { id: "midnight-shag-coat", code: "O06", name: "Midnight Shag Faux Fur Coat", price: 179, cat: "outerwear", img: "img/outwear/outwear-06.jpg", drop: "core", added: -52, sizes: CLOTHES, color: "Jet black", focus: [45, 65],
      desc: "Enormous jet black shaggy faux fur coat with a stand collar you can hide your whole face in.",
      details: ["Long-pile faux fur", "Stand collar", "Hidden hooks", "Oversized, mid-thigh"] },
    { id: "afghan-shag-coat", code: "O07", name: "Afghan Shag Suede Coat", price: 198, cat: "outerwear", img: "img/outwear/outwear-07.jpg", drop: "core", added: -53, sizes: CLOTHES, color: "Taupe suede / grey shag", focus: [30, 50],
      desc: "Taupe faux suede coat trimmed with curly shaggy faux fur along the front and cuffs. Very 70s rockstar girlfriend.",
      details: ["Faux suede", "Curly faux fur trim", "Tie waist", "Knee length"] },
    { id: "rib-knit-leather-bomber", code: "O08", name: "Rib Knit Leather Bomber", price: 139, cat: "outerwear", img: "img/outwear/outwear-08.jpg", tag: "BESTSELLER", drop: "core", added: -54, sizes: CLOTHES, color: "Black", focus: [50, 50],
      desc: "Fitted faux leather bomber with chunky rib-knit sleeves and waistband, zip pockets and a snap collar.",
      details: ["Faux leather + rib knit", "Zip chest pocket", "Snap collar", "Fitted, hip length"] },
    { id: "washed-out-biker", code: "O09", name: "Washed Out Biker Jacket", price: 165, cat: "outerwear", img: "img/outwear/outwear-09.jpg", tag: "NEW", drop: "core", added: -55, sizes: CLOTHES, color: "Washed black", focus: [45, 55],
      desc: "Vintage-washed black biker with worn edges, a belted hem and asymmetric zip. Looks inherited from someone cooler.",
      details: ["Washed faux leather", "Asymmetric zip", "Belted hem", "Relaxed fit"] },
    { id: "snow-fox-cropped-fur", code: "O10", name: "Snow Fox Cropped Faux Fur", price: 145, cat: "outerwear", img: "img/outwear/outwear-10.jpg", drop: "core", added: -56, sizes: CLOTHES, color: "Snow grey", focus: [50, 50],
      desc: "Cropped fluffy faux fur jacket in snow grey with a big notch collar. Goes with low-rise flares and nothing else matters.",
      details: ["Long-pile faux fur", "Notch collar", "Hook closure", "Cropped"] },
    { id: "leopard-fur-hoodie", code: "O11", name: "Leopard Fur Zip Hoodie", price: 119, cat: "outerwear", img: "img/outwear/outwear-11.jpg", tag: "NEW", drop: "core", added: -57, sizes: CLOTHES, color: "Leopard", focus: [50, 55],
      desc: "Plush leopard faux fur hoodie with a zip front, brown rib cuffs and a deep hood.",
      details: ["Plush faux fur", "Rib knit cuffs", "Two-way zip", "Oversized hood"] },
    { id: "lone-wolf-coat", code: "O12", name: "Lone Wolf Faux Fur Coat", price: 189, cat: "outerwear", img: "img/outwear/outwear-12.jpg", tag: "LAST 2", hot: true, drop: "core", added: -58, sizes: CLOTHES, color: "Wolf grey", focus: [40, 40],
      desc: "Long wolf-grey faux fur coat with a hood and wide sleeves. The main character coat.",
      details: ["Long-pile faux fur", "Hooded", "Satin lining", "Knee length"] },
    { id: "stand-collar-moto", code: "O13", name: "Stand Collar Moto Jacket", price: 119, cat: "outerwear", img: "img/outwear/outwear-13.jpg", drop: "core", added: -59, sizes: CLOTHES, color: "Black", focus: [55, 50],
      desc: "Clean, fitted black faux leather moto jacket with a stand collar, quilted shoulders and zip pockets.",
      details: ["Faux leather", "Stand collar", "Quilted shoulder panels", "Fitted"] }
  ];
})();
